### ISSUE TITLE
ComputerCraft needed for ZeroCore 1

### ISSUE THREAD

**Issue by hypersmc** [ZeroNoRyouki/ZeroCore2#1]
> Could not find dan200.computercraft:ComputerCraft:1.80pr1-build5.
  Searched in the following locations:
    - https://files.minecraftforge.net/maven/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.pom
    - https://files.minecraftforge.net/maven/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.jar
    - https://repo.maven.apache.org/maven2/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.pom
    - https://repo.maven.apache.org/maven2/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.jar
    - https://libraries.minecraft.net/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.pom
    - https://libraries.minecraft.net/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.jar
    - http://maven.zerono.it/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.pom
    - http://maven.zerono.it/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.jar
    - file:/C:/Users/me/.gradle/caches/minecraft/deobfedDeps/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.pom
    - file:/C:/Users/me/.gradle/caches/minecraft/deobfedDeps/dan200/computercraft/ComputerCraft/1.80pr1-build5/ComputerCraft-1.80pr1-build5.jar
    - file:/C:/Users/me/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2838/snapshot/20171003/ComputerCraft-1.80pr1-build5.jar
    - file:/C:/Users/me/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2838/snapshot/20171003/ComputerCraft.jar
  Required by:
      project : > it.zerono.mods.zerocore:zerocore:1.12.2-0.1.2.8

**Comment by ZeroNoRyouki** [comment]
You can find the CC maven here: http://cc.crzd.me/maven/

**Comment by hypersmc** [comment]
> You can find the CC maven here: http://cc.crzd.me/maven/

Why does it require CC?
It's not stated anywhere. Not even in the installation.

**Comment by ZeroNoRyouki** [comment]
ZC contains the base support for computers peripherals (CC/OC) used by my mods.

What installation?

**Comment by hypersmc** [comment]
> ZC contains the base support for computers peripherals (CC/OC) used by my mods.
> 
> What installation?

This installation: http://zerono.it/zerocore-multiblock-api-tutorial/

**Comment by ZeroNoRyouki** [comment]
Yup, it's old. 

And speacking about old, why 1.12 and not 1.16.4?

**Comment by hypersmc** [comment]
> Yup, it's old.
> 
> And speacking about old, why 1.12 and not 1.16.4?

My friend and I have refused to go beyond 1.12.2.

**Comment by ZeroNoRyouki** [comment]
The multiblock API deals with what a MC world is made of, blocks.

Then, if some of the blocks you want to handle are fluid blocks, it's up to you what you do with them. 

You can see an example here : https://github.com/ZeroNoRyouki/BigReactors/blob/c26d7ba0b5e28e5b6eb4fd5d4b37da641866144f/src/main/java/erogenousbeef/bigreactors/common/multiblock/MultiblockReactor.java#L654

**Comment by hypersmc** [comment]
> The multiblock API deals with what a MC world is made of, blocks.
> 
> Then, if some of the blocks you want to handle are fluid blocks, it's up to you what you do with them.
> 
> You can see an example here : https://github.com/ZeroNoRyouki/BigReactors/blob/c26d7ba0b5e28e5b6eb4fd5d4b37da641866144f/src/main/java/erogenousbeef/bigreactors/common/multiblock/MultiblockReactor.java#L654

When I mean fluid I mean fluid as an input. like items and energy.

**Comment by ZeroNoRyouki** [comment]
That has to be handled by your blocks.

The MB API if a framework to build multublock structures but it does not provide functionalities for those blocks. So if, say, one of the block of your mb need to accept items or fluids you need to implement that functionaly yourself, like for any other block

You may found some helper classes in the lib package of ZC that could help you, but not as much as you would find in the 1.16.4 version.
