### ISSUE TITLE
Possiblity to allow for Porting to Fabric

### ISSUE THREAD

**Issue by Dragon-Seeker** [ZeroNoRyouki/ZeroCore2#10]
I saw that there was already a issue opened about the license and was wondering if it was possible to port this lib to Fabric in anyway? I know its ARR and was wondering if I could get permission to do such?

**Comment by ZeroNoRyouki** [comment]
I'm already porting ZC and ER to Fabric

**Comment by Dragon-Seeker** [comment]
Was going to take a crack at such since Create Porting Lib exists and one of my friends was going to get it done.

**Comment by Dragon-Seeker** [comment]
Is this a no for Porting the Lib?

**Comment by ZeroNoRyouki** [comment]
> Is this a no for Porting the Lib?
Yes, since I'm already doing it
