### ISSUE TITLE
CTD After Update ZeroCore2-1.19.2-2.1.33.jar

### ISSUE THREAD

**Issue by zeziba** [ZeroNoRyouki/ZeroCore2#14]
Greetings,

After updating to 2.1.33 the game will CTD after launch, downgrading to 2.1.32 fixes this issue.

Attached is the crash log.
[crash-2023-04-10_08.46.37-client.txt](https://github.com/ZeroNoRyouki/ZeroCore2/files/11191241/crash-2023-04-10_08.46.37-client.txt)

**Comment by ZeroNoRyouki** [comment]
Hi, thank you for the report.
I've just re-uploaded the jar.

Thank you
Z
