### ISSUE TITLE
[zero core] 2.1.35 release for 1.18.2 registered as 1.16.5

### ISSUE THREAD

**Issue by ColonelGerdauf** [ZeroNoRyouki/ZeroCore2#15]
The release for the latest, written in the file as 1.18.2, is put in the 1.16.5 slot on Modrinth. This will cause needless confusion and compatibility concerns, particularly when people download the library through the loaders.

**Comment by ZeroNoRyouki** [comment]
Fixed!

Thank you for letting me know.
Z
