### ISSUE TITLE
Crash With Block Text

### ISSUE THREAD

**Issue by ReportBot9009** [ZeroNoRyouki/ZeroCore2#16]
Hello,
I have a heavily modified version of Enigmatica 2 Expert. I am trying to update zerocore from 0.1.2.3 to 0.1.2.9. 
Here is crash report: https://mclo.gs/Won6jUv

Also, all of the text turns into large white blocks, so you are unable to read anything. 

Thanks

**Comment by ZeroNoRyouki** [comment]
Update Extreme Reactors to the last version for 1.12.2
