### ISSUE TITLE
No license is provided

### ISSUE THREAD

**Issue by ChristopherJTrent** [ZeroNoRyouki/ZeroCore2#2]
It's unclear if permission has actually been given to use ZeroCore2 in other mods, including a LICENSE.txt or similar would fix that.

**Comment by ZeroNoRyouki** [comment]
It's specified in the mod page on [curseforge](https://www.curseforge.com/minecraft/mc-mods/zerocore). TLTR: yes, you can use ZeroCore(1-2) as a dependency of other mods.
