### ISSUE TITLE
Hello there question about enigmatica 2 expert

### ISSUE THREAD

**Issue by Kuktar** [ZeroNoRyouki/ZeroCore2#4]
So i just installed enigmatica 2 expert modpack and i updated all mods to most recent version. when i loaded into my server i noticed the recipes were normal and not the expert ones. i started to investigate and went through so many diffrent approaches and found that if i downgrade zerocore2 to version 1.12.2-0.1.2.8 and also i have to downgrade extreme reactors. 

it works just fine with the older version of zerocore2 and extremereactors. I am not even sure whats going on other than maybe some block ids or somthing im not even familer with is happening. i suppose i dont HAVE to have the newest version of extreme reactors but i thought it was odd. thank you for the great mods!

**Comment by matt-laird** [comment]
Enigmatica changes the recipes based off of the difficulty you choose, this isn't a problem with the Lib or Extreme reactors.
