### ISSUE TITLE
Concurrent Modification exception in multiblock registry

### ISSUE THREAD

**Issue by justastranger** [ZeroNoRyouki/ZeroCore2#5]
https://pastebin.com/kh8bbiEP

Crash occurred as soon as I placed a reactor casing block for the first time. Loading the save back up after the crash allowed me to continue placing blocks with no issue.

**Comment by ZeroNoRyouki** [comment]
Thank you for the report. Is this a custom modpack or something that I can download?
Can you reproduce the crash?
Thank you
Z

**Comment by justastranger** [comment]
This is a custom modpack for personal use. I haven't tried to reproduce it yet.

**Comment by KitsuneAlex** [comment]
Actually, i think this is not the registry but something related to the ModelData in the multiblock model system. I haven't looked into it much yet but do you happen to have a Sodium fork installed @justastranger ?

**Comment by KitsuneAlex** [comment]
If this really was the issue, i just fixed it and imma submit a PR.

**Comment by ZeroNoRyouki** [comment]
uhm Magnesium was not in the pack from what I can see but I'll check this again with it installed. For the CuboidPartVariantsModelDataCache thing too

**Comment by KitsuneAlex** [comment]
Okay fair enough, i definitly fixed a CME-related crash tho, check the PR :D
