### ISSUE TITLE
Most recent version (8/15/2021) shows 'virus or unwanted software' warning in CurseForge

### ISSUE THREAD

**Issue by archonsd** [ZeroNoRyouki/ZeroCore2#7]
Team,
Only the 8/15/2021 (most recent version as of today) shows a warning in the CurseForge GUI that it contains either a virus or unwanted software, and refuses to allow install.  I rolled back to 8/6/2021 to continue using it.  

You can see the error [here](https://i.ibb.co/PgNDWN2/Screenshot-2021-08-18-213830.png).

**Comment by ZeroNoRyouki** [comment]
I'll check the file ASAP but it's probably related to this: 

https://forums.malwarebytes.com/topic/277792-curseforge-modpacks-false-positives/?tab=comments#comment-1475682

**Comment by ZeroNoRyouki** [comment]
I've downloaded the file from CF and scanned it with a bunch of AV but nothing strange was found
