### ISSUE TITLE
Ticking block entity issue with ZeroCore and Extreme Reactors

### ISSUE THREAD

**Issue by AnCasper** [ZeroNoRyouki/ZeroCore2#9]
Found a problem, when items go through a pipe or into a container or ReProccessor the chunk can get corrupted.

Tested a few times and it is temperamental, sometimes it will work fine and the next it won't.

[Crash.txt](https://github.com/ZeroNoRyouki/ZeroCore2/files/7645568/Crash.txt)
 
Edit: it is definitely related to the ReProccessor :) gl

**Comment by ZeroNoRyouki** [comment]
Thank you for the report. I will release a fix today
Z

**Comment by ZeroNoRyouki** [comment]
ZC 1.16.5-2.1.7 and ER 1.16.5-2.0.33 are out. 1.17 following.

**Comment by AnCasper** [comment]
Thank you so much for fixing this issue promptly!

**Comment by ZeroNoRyouki** [comment]
You are welcome
